
-- Dirty read
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	SELECT * FROM Employee
COMMIT TRAN


-- Non-reapeatable reads
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	UPDATE Employee
	SET firstName = 'Will'
	WHERE employeeId = 264
COMMIT TRAN

-- Phantom reads
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	INSERT INTO Employee(firstName, lastName, birthDate, CNP)
	VALUES ('Phantom', 'Phantom', '1000-10-10', 1001010020105)
COMMIT TRAN

-- Deadlock

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	UPDATE WorksOn
	SET toDate = '2020-05-21'
	WHERE employeeId = 1

	WAITFOR DELAY '00:00:10'

	UPDATE Employee
	SET lastName = 'Johnson'
	WHERE employeeId = 1
	WAITFOR DELAY '00:00:10'
COMMIT TRAN



